steps:
- id: build-img
  uses: docker://docker:19.03.10
  args:
  - build
  -   --build-arg=CEPH_RELEASE=v15.2.4
  -   --tag=jcnitdgp25/cls-builder:v15.2.4
  -   --file=docker/builder/Dockerfile
  -   .

- id: build
  skip_pull: true
  uses: docker://jcnitdgp25/cls-builder:v15.2.4
  runs: [bash, -euxc]
  args:
  - |
    mkdir -p build/
    cd build/
    cmake ..
    make VERBOSE=1

- id: test
  skip_pull: true
  uses: docker://jcnitdgp25/cls-builder:v15.2.4
  runs: [bash, -euxc]
  env:
    LD_LIBRARY_PATH: /usr/local/lib64
  args:
  - |
    cp build/lib/libcls_arrow.so* /usr/lib64/rados-classes/
    scripts/micro-osd.sh test-cluster /etc/ceph
    build/bin/cls_arrow_test
