steps:

- id: dev-init
  uses: docker://alpine/git:v2.24.3
  runs: [sh]
  args:
  - -c
  - |
    set -e
    git clone \
      --recursive \
      --depth 1 \
      --shallow-submodules \
      --branch nautilus \
      https://github.com/ceph/ceph

    ln -s ../../../src ceph/src/cls/tabular

    echo "add_subdirectory(tabular)" >> ceph/src/cls/CMakeLists.txt

- id: build
  uses: docker://uccross/skyhookdm-builder:nautilus
  runs: [bash]
  args: [scripts/build.sh]
  env:
    # travis config: 4 threads, release build
    CMAKE_FLAGS: "-DBOOST_J=4 -DCMAKE_BUILD_TYPE=Release -DWITH_MANPAGE=OFF -DWITH_BABELTRACE=OFF -DWITH_MGR_DASHBOARD_FRONTEND=OFF"
    BUILD_THREADS: "4"

    ## debug config: 16 threads, debug build
    # CMAKE_FLAGS: "-DBOOST_J=16 -DCMAKE_BUILD_TYPE=Debug -DWITH_MANPAGE=OFF -DWITH_BABELTRACE=OFF -DWITH_MGR_DASHBOARD_FRONTEND=OFF"
    # BUILD_THREADS: "16"

- id: build-rook-img
  uses: docker://docker:19.03.10
  args:
  - build
  -   --build-arg=CEPH_RELEASE=v14.2.9
  -   --tag=uccross/skyhookdm-ceph:v14.2.9
  -   --file=docker/Dockerfile.release
  -   .

- id: test
  uses: docker://uccross/skyhookdm-ceph:v14.2.9
  skip_pull: true
  runs: [bash]
  env:
    LD_LIBRARY_PATH: /usr/lib64/ceph
  args: [scripts/run_tests.sh]

- id: push-img
  uses: docker://docker:19.03.3
  secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
  runs: [sh]
  args:
  - -c
  - |
    # only push from master branch
    if [[ $GIT_BRANCH == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      docker push uccross/skyhookdm-ceph:v14.2.9
    fi
