steps:
- id: build
  uses: ./docker/builder
  runs: [bash, -euxc]
  args:
  - |
    mkdir -p build/
    cd build/
    cmake ..
    make VERBOSE=1

- id: build-rook-img
  uses: docker://docker:19.03.10
  args:
  - build
  -   --build-arg=CEPH_RELEASE=v14.2.9
  -   --tag=uccross/skyhookdm-ceph:v14.2.9
  -   --file=docker/Dockerfile.release
  -   .

- id: test
  uses: ./docker/builder
  runs: [bash, -euxc]
  args:
  - |
    cp ceph/build/bin/cls_sdk_test /usr/bin/ 
    cp ceph/build/lib/arrow_cls.so* /usr/lib64/rados-classes/
    TEST_DIR="test"
    CONF_DIR="/etc/ceph"
    scripts/mircro-osd.sh $TEST_DIR $CONF_DIR
    sripts/run_tests.sh  
