ARG CEPH_RELEASE="v14.2.9"
FROM ceph/ceph:${CEPH_RELEASE}

RUN yum install -y https://apache.bintray.com/arrow/centos/7/apache-arrow-release-latest.rpm && \
    yum install -y \
      re2-devel \
      arrow-devel \
      parquet-devel && \
    yum clean all

COPY build/bin/run-query build/bin/ceph_test_skyhook_query /usr/bin/
COPY build/lib/libcls_tabular.so.1.0.0 /usr/lib64/rados-classes/
